import React from 'react';
import { logger } from '../logger';

export default function Home({ onNavigate }) {
  const handleFeatureClick = (feature) => {
    logger.info(`User clicked on ${feature} feature`);
    onNavigate(feature);
  };

  return (
    <div className="fade-in">
      <h2>Welcome to Ron Hub</h2>
      <p style={{ color: 'var(--text-secondary)', marginBottom: '3rem' }}>
        Choose a feature to get started.
      </p>

      <div className="features-grid">
        <div 
          className="feature-card glass-panel"
          onClick={() => handleFeatureClick('quiz')}
          style={{ cursor: 'pointer' }}
        >
          <div className="feature-icon">📝</div>
          <h3>Quiz</h3>
          <p>Test your knowledge with quizzes generated by Ron.</p>
          <span className="feature-link">Open Quiz →</span>
        </div>

        <div 
          className="feature-card glass-panel"
          onClick={() => handleFeatureClick('playlist')}
          style={{ cursor: 'pointer' }}
        >
          <div className="feature-icon">🎵</div>
          <h3>Playlist</h3>
          <p>Manage and create your custom playlists.</p>
          <span className="feature-link">Open Playlist →</span>
        </div>
      </div>
    </div>
  );
}
