import React, { useEffect, useState } from 'react';
import { fetchQuizzes } from '../api';

export default function QuizList({ onSelectQuiz }) {
  const [quizzes, setQuizzes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const loadQuizzes = async () => {
      try {
        const data = await fetchQuizzes();
        setQuizzes(data.quizzes || []);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    loadQuizzes();
  }, []);

  if (loading) return <div className="fade-in subtitle">Loading quizzes...</div>;
  if (error) return <div className="fade-in error-banner">Error: {error}</div>;
  if (quizzes.length === 0) return <div className="fade-in empty-state glass-panel">No quizzes found. Ask Ron to generate one!</div>;

  return (
    <div className="fade-in">
      <h2>Available Quizzes</h2>
      <p className="subtitle">
        Select a quiz generated by Ron to start practicing.
      </p>
      
      <div className="quiz-grid">
        {quizzes.map((quiz, index) => (
          <div 
            key={index} 
            className="quiz-card glass-panel"
            onClick={() => onSelectQuiz(quiz)}
          >
            <div className="quiz-icon">📝</div>
            <h3 className="quiz-title">{quiz.replace('.json', '').replace(/_/g, ' ')}</h3>
            <span className="quiz-start-link">Start Quiz →</span>
          </div>
        ))}
      </div>
    </div>
  );
}
